### ISSUE TITLE
sync-backlight error (tee: /sys/class/backlight/card0-eDP-2-backlight/brightness: No such file or directory)

### ISSUE THREAD

**Issue by bitodt** [alesya-h/zenbook-duo-2024-ux8406ma-linux#5]
When running `duo watch-backlight` I get the error
```
tee: /sys/class/backlight/card0-eDP-2-backlight/brightness: No such file or directory
147
Setting up watches.
Watches established.
```
Doing `ls -l /sys/class/backlight/` I get
```
lrwxrwxrwx 1 root root 0 May 29 07:25 asus_screenpad -> ../../devices/platform/asus-nb-wmi/backlight/asus_screenpad
lrwxrwxrwx 1 root root 0 May 29 07:25 card1-eDP-2-backlight -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-2/card1-eDP-2-backlight
lrwxrwxrwx 1 root root 0 May 29 07:25 intel_backlight -> ../../devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight
```
It seems like my second screen's backlight is missing from Linux.

Also, `find /sys/devices/pci0000\:00/ -name *backlight*` returns
```
/sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-2/card1-eDP-2-backlight
/sys/devices/pci0000:00/0000:00:02.0/drm/card1/card1-eDP-1/intel_backlight
```

My backlight controls only affect the top screen, while the bottom stays intact.

Any ideas?

Specs: 

- Zenbook Duo UX8406MA PZ058X (Ultra 9, 32GB Ram, 3k Resolution, 2TB disk)
- OS: Ubuntu 24.04
- Kernel: 6.8.0-31-generic

**Comment by bitodt** [comment]
It seems my top screen is named intel_backlight and bottom screen is card1-eDP-2-backlight.
Can be controlled individually if needed.

**Comment by janitza-nase** [comment]
Same problem here. Could you give any more concise hint, HOW you solved this? Googling around for changing name of devices like monitors has not given any concrete clue.

How did you manage renaming top screen "intel_backlight" to "card0-eDP-2-backlight"?

**Comment by bitodt** [comment]
I didn't change the name of the monitor. I don't know if/how that can be done.
I adjusted my scripts to intel_backlight instead of card0-eDP-2-backlight.

**Comment by NaScha** [comment]
Ah okay, thanks. I have exactly the same output like you for 
` find /sys/devices/pci0000\:00/ -name *backlight*
`

adjusted my scripts to intel_backlight instead of card0-eDP-2-backlight (like you). I do not get any errors when manually executing the brightness sync commands, but my bottom screen's brightness does not sync - it remains like it is. After having replaced  card0-eDP-2-backlight with  card1-eDP-2-backlight in my scripts (instead of intel_backlight) it works!!! So in my case, it's the other way round. Anyway, now everything works like a charm: auto rotate, panel mapping and brightness sync. Great!
